from __future__ import annotations

import hashlib
import json
import os
import secrets
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles

from insight_engine.web_server import InsightWebService

app = FastAPI(title="INSIGHT Engine Web Dashboard", version="1.1")
service = InsightWebService()

BASE_DIR = Path(__file__).resolve().parent
STATIC_DIR = BASE_DIR / "static"
app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")

# Optional access protection.
# Set INSIGHT_ACCESS_CODE on Render to enable login.
# Set INSIGHT_SINGLE_DEVICE_LOCK=1 to lock the dashboard to the first browser/device that logs in.
AUTH_CODE = os.getenv("INSIGHT_ACCESS_CODE", "").strip()
SINGLE_DEVICE_LOCK = os.getenv("INSIGHT_SINGLE_DEVICE_LOCK", "0").strip() == "1"
LOCK_FILE = Path(os.getenv("INSIGHT_DEVICE_LOCK_FILE", str(BASE_DIR / "insight_device_lock.json")))
COOKIE_NAME = "insight_session"
SESSION_DAYS = int(os.getenv("INSIGHT_SESSION_DAYS", "90"))

# In-memory sessions for normal login mode. In single-device mode, the lock file also stores the active session hash.
active_sessions: set[str] = set()


def _sha256(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _load_lock() -> dict[str, Any] | None:
    try:
        if LOCK_FILE.exists():
            return json.loads(LOCK_FILE.read_text(encoding="utf-8"))
    except Exception:
        return None
    return None


def _save_lock(data: dict[str, Any]) -> None:
    LOCK_FILE.parent.mkdir(parents=True, exist_ok=True)
    LOCK_FILE.write_text(json.dumps(data, indent=2), encoding="utf-8")


def _auth_enabled() -> bool:
    return bool(AUTH_CODE)


def _device_id_from_request(request: Request) -> str:
    # This is generated by the browser and stored in localStorage.
    # Browsers do not expose MAC addresses, so this is the practical web-safe binding method.
    return request.headers.get("x-insight-device", "").strip()


def _request_is_https(request: Request) -> bool:
    return request.url.scheme == "https" or request.headers.get("x-forwarded-proto", "").lower() == "https"


def _is_authorized(request: Request) -> bool:
    if not _auth_enabled():
        return True

    session_token = request.cookies.get(COOKIE_NAME, "").strip()
    if not session_token:
        return False
    session_hash = _sha256(session_token)

    if SINGLE_DEVICE_LOCK:
        device_id = _device_id_from_request(request)
        if not device_id:
            return False
        lock = _load_lock()
        if not lock:
            return False
        return (
            lock.get("device_hash") == _sha256(device_id)
            and lock.get("session_hash") == session_hash
        )

    return session_hash in active_sessions


def _require_auth(request: Request) -> None:
    if not _is_authorized(request):
        raise HTTPException(status_code=401, detail="Login required")


@app.on_event("startup")
async def startup_event() -> None:
    if os.getenv("INSIGHT_AUTOSTART", "1") == "1":
        await service.start()


@app.on_event("shutdown")
async def shutdown_event() -> None:
    await service.stop()


@app.get("/")
async def index():
    return FileResponse(STATIC_DIR / "index.html")


@app.get("/health")
async def health():
    state = await service.state()
    return {"ok": state["status"].startswith("Live") or state["status"] in {"Starting", "Stopped"}, "status": state["status"]}


@app.get("/api/auth/status")
async def api_auth_status(request: Request):
    return {
        "auth_required": _auth_enabled(),
        "authorized": _is_authorized(request),
        "single_device_lock": SINGLE_DEVICE_LOCK,
        "device_locked": bool(_load_lock()) if SINGLE_DEVICE_LOCK else False,
    }


@app.post("/api/login")
async def api_login(request: Request):
    if not _auth_enabled():
        return {"ok": True, "message": "Authentication is disabled."}

    try:
        data = await request.json()
    except Exception:
        data = {}

    code = str(data.get("code", "")).strip()
    device_id = str(data.get("device_id", "")).strip()

    if code != AUTH_CODE:
        raise HTTPException(status_code=403, detail="Wrong access code")

    if SINGLE_DEVICE_LOCK and not device_id:
        raise HTTPException(status_code=400, detail="Device ID missing")

    session_token = secrets.token_urlsafe(32)
    session_hash = _sha256(session_token)
    active_sessions.add(session_hash)

    if SINGLE_DEVICE_LOCK:
        device_hash = _sha256(device_id)
        existing = _load_lock()
        if existing and existing.get("device_hash") != device_hash:
            raise HTTPException(
                status_code=423,
                detail="This dashboard is already locked to another device. Reset the device lock to use a new phone/laptop.",
            )

        lock = existing or {
            "device_hash": device_hash,
            "first_seen_at": _now(),
            "first_user_agent": request.headers.get("user-agent", ""),
        }
        lock["session_hash"] = session_hash
        lock["last_login_at"] = _now()
        lock["last_user_agent"] = request.headers.get("user-agent", "")
        _save_lock(lock)

    response = JSONResponse({"ok": True, "single_device_lock": SINGLE_DEVICE_LOCK})
    response.set_cookie(
        COOKIE_NAME,
        session_token,
        max_age=SESSION_DAYS * 24 * 60 * 60,
        httponly=True,
        secure=_request_is_https(request),
        samesite="lax",
    )
    return response


@app.post("/api/logout")
async def api_logout():
    response = JSONResponse({"ok": True})
    response.delete_cookie(COOKIE_NAME)
    return response


@app.get("/api/state")
async def api_state(request: Request):
    _require_auth(request)
    return await service.state()


@app.post("/api/start")
async def api_start(request: Request):
    _require_auth(request)
    await service.start()
    return await service.state()


@app.post("/api/stop")
async def api_stop(request: Request):
    _require_auth(request)
    await service.stop()
    return await service.state()
